[package]
name = "algorsand"
version = "0.1.0"
edition = "2018"

[dependencies]
data-encoding = "2"
ed25519 = "1"
ed25519-dalek = "1"
lazy_static = "1"
libsecp256k1 = "0.7"
rand = "0.8"
rmp = "0.8"
serde = "1"
serde_json = "1"
sha2 = "0.9"
