version: 2.1

orbs:
  rust: circleci/rust@1.6.0
workflows:
  production:
    jobs:
      - rust/lint-test-build:
          version: '1.56.0'
          release: true
          working_directory: ~/algorsand