// Copyright (C) 2021 Quentin M. Kniep <hello@quentinkniep.com>
// Distributed under terms of the MIT license.

use std::collections::HashMap;
use std::time::Duration;

use super::Local;

impl Default for Local {
    fn default() -> Self {
        Self {
            version: 0,
            account_updates_stats_interval: Duration::from_millis(5000),
            accounts_rebuild_synchronous_mode: 1,
            announce_participation_key: true,
            archival: false,
            base_logger_debug_level: 4,
            block_service_custom_fallback_endpoints: "".to_owned(),
            broadcast_connections_limit: -1,
            cadaver_size_target: 1_073_741_824,
            catchpoint_file_history_length: 365,
            catchpoint_interval: 10000,
            catchpoint_tracking: 0,
            catchup_block_download_retry_attempts: 1000,
            catchup_block_validate_mode: 0,
            catchup_failure_peer_refresh_rate: 10,
            catchup_gossip_block_fetch_timeout_sec: 4,
            catchup_http_block_fetch_timeout_sec: 4,
            catchup_ledger_download_retry_attempts: 50,
            catchup_parallel_blocks: 16,
            connections_rate_limiting_count: 60,
            connections_rate_limiting_window_seconds: 1,
            dns_bootstrap_id: "<network>.algorand.network".to_owned(),
            dns_security_flags: 1,
            deadlock_detection: 0,
            disable_localhost_connection_rate_limit: true,
            disable_networking: false,
            disable_outgoing_connection_throttling: false,
            enable_account_updates_stats: false,
            enable_agreement_reporting: false,
            enable_agreement_time_metrics: false,
            enable_assemble_stats: false,
            enable_block_service: false,
            enable_block_service_fallback_to_archiver: true,
            enable_catchup_from_archive_servers: false,
            enable_developer_api: false,
            enable_gossip_block_service: true,
            enable_incoming_message_filter: false,
            enable_ledger_service: false,
            enable_metric_reporting: false,
            enable_outgoing_network_message_filtering: true,
            enable_ping_handler: true,
            enable_process_block_stats: false,
            enable_profiler: false,
            enable_request_logger: false,
            enable_top_accounts_reporting: false,
            endpoint_address: "127.0.0.1:0".to_owned(),
            fallback_dns_resolver_address: "".to_owned(),
            force_relay_messages: false,
            gossip_fanout: 4,
            incoming_connections_limit: 10_000,
            incoming_message_filter_bucket_count: 5,
            incoming_message_filter_bucket_size: 512,
            is_indexer_active: false,
            ledger_synchronous_mode: 2,
            log_archive_max_age: "".to_owned(),
            log_archive_name: "node.archive.log".to_owned(),
            log_size_limit: 1_073_741_824,
            max_catchpoint_download_duration: Duration::from_secs(7200),
            max_connections_per_ip: 30,
            min_catchpoint_file_download_bytes_per_second: 20_480,
            net_address: "".to_owned(),
            network_message_trace_server: "".to_owned(),
            network_protocol_version: "".to_owned(),
            node_exporter_listen_address: ":9100".to_owned(),
            node_exporter_path: "./node_exporter".to_owned(),
            optimize_accounts_database_on_startup: false,
            outgoing_message_filter_bucket_count: 3,
            outgoing_message_filter_bucket_size: 128,
            participation_keys_refresh_interval: Duration::from_secs(60),
            peer_connections_update_interval: 3600,
            peer_ping_period_seconds: 0,
            priority_peers: HashMap::new(),
            public_address: "".to_owned(),
            reconnect_time: Duration::from_secs(60),
            reserved_fds: 256,
            rest_read_timeout_seconds: 15,
            rest_write_timeout_seconds: 120,
            run_hosted: false,
            suggested_fee_block_history: 3,
            suggested_fee_sliding_window_size: 50,
            tls_cert_file: "".to_owned(),
            tls_key_file: "".to_owned(),
            telemetry_to_log: true,
            tx_pool_exponential_increase_factor: 2,
            tx_pool_size: 15_000,
            tx_sync_interval_seconds: 60,
            tx_sync_serve_response_size: 1_000_000,
            tx_sync_timeout_seconds: 30,
            use_xforwarded_for_address_field: "".to_owned(),
            verified_transcations_cache_size: 30_000,
        }
    }
}
